[package]
name = "RustWindow"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = "0.25.0"
winapi = { version = "0.3", features = ["dwmapi", "winuser", "libloaderapi", "windef"] }
lazy_static = "1.4"

[build-dependencies]
winres = "0.1"
